### ISSUE TITLE
Discovering images with multiple packages at different versions

### ISSUE THREAD

**Issue by amouat** [chainguard-images/meta#11]
For some of our images, users may be interested in the versions of multiple packages. For example in the ko image, both the ko version and the go version are relevant and important. Users may want the latest version of ko but an older version of Go for compatibility. How should we support this and help users to find the right versions?

If we look at Docker Hub, the [wordpress image](https://hub.docker.com/_/wordpress) has tags such as `6.0.2-php8.1-fpm`, indicating both wordpress version and PHP version.

We can do the same or similar, but it's also possible to create a registry UI capable of filtering on annotations or SBOMs that include this data.

Thoughts?

**Comment by patflynn** [comment]
we're fixing this with better tagging.
