### ISSUE TITLE
Support Ruby Images

### ISSUE THREAD

**Issue by amouat** [chainguard-images/meta#12]
As title, need support for ruby images https://www.ruby-lang.org/en/

**Comment by imjasonh** [comment]
https://git.alpinelinux.org/aports/tree/main/ruby/APKBUILD

**Comment by dlorenc** [comment]
Someone requested version 3.0!

**Comment by patflynn** [comment]
@kaniini do we have a tracking issue for the multi-version package work to block this issue on?

**Comment by imjasonh** [comment]
> @kaniini do we have a tracking issue for the multi-version package work to block this issue on?

JDK and postgres packages are now named based on their version (`openjdk-11-11.0.7.8-r0.apk`, `postgresql-11,11.17-r0.apk`), so following that I guess our Ruby packages could be:

- `ruby-3.1-3.1.2-r0.apk` ([current](https://github.com/wolfi-dev/os/blob/main/ruby.yaml), renamed)
- `ruby-3.0-3.0.4-r0.apk` (new)

**Comment by patflynn** [comment]
do we need a tracking issue for a ruby chainguard image?

**Comment by patflynn** [comment]
or two?

**Comment by imjasonh** [comment]
Let's use this to track the images too.

**Comment by imjasonh** [comment]
The images are live: https://github.com/chainguard-images/ruby

The readme is a little broek at the moment because it doesn't have a `:latest` tag, but we might just fix that by changing how the READMEs are updated.
