### ISSUE TITLE
Support Java images

### ISSUE THREAD

**Issue by amouat** [chainguard-images/meta#2]
We should add some Java images. Both JDK and JRE. Alpine seems to have several packages already, could also grab binaries from adoptium.

 - [x] https://github.com/chainguard-images/images/issues/91
 - [x] https://github.com/chainguard-images/jdk/issues/4

https://github.com/chainguard-images/meta/issues/2#tasklist-block-d56163dc-9773-44d2-84a3-1c79e3f0db7d

**Comment by amouat** [comment]
Let's do this, adding to the next deadline.

**Comment by amouat** [comment]
@patflynn here's the tracking issue.

**Comment by rawlingsj** [comment]
We now have wolfi packages for maven, JDK + JRE 11 and 17.  Initially there was a PR on the existing JDK images repo https://github.com/chainguard-images/jdk/pull/15 but as we're moving to the monorepo we're focussing on releasing from [here](https://github.com/chainguard-images/images/tree/main/images).  The aim is being able to release from the monorepo to be complete EOW

**Comment by stevehipwell** [comment]
👀 new mono repo!?

**Comment by tuananh** [comment]
> Images are now built and published via the new images mono repo https://github.com/chainguard-images/images/

404 for me. private ?

**Comment by amouat** [comment]
Yes, we'll open it up shortly. Just want to make sure it works first!

**Comment by amouat** [comment]
@stevehipwell @tuananh I think you're both aware, but the "monorepo" is now up and running at  https://github.com/chainguard-images/images/. We're still working on ARM support, after that we'll transition the images to default to the wolfi versions.

@rawlingsj how is the TCK stuff going? I'm wondering if we should open a separate issue to track that so that we can close this one.

**Comment by stevehipwell** [comment]
> We're still working on ARM support, after that we'll transition the images to default to the wolfi versions.

@amouat are there ARM64 images available? Looking in the repo it looks like everything (I only looked a JDK & Ruby) is based on Wolfi?

**Comment by rawlingsj** [comment]
> how is the TCK stuff going? I'm wondering if we should open a separate issue to track that so that we can close this one.

Created issue https://github.com/chainguard-images/meta/issues/24.  I've not started on this yet.  Working through the auto package updates work first.

**Comment by amouat** [comment]
@stevehipwell JDK and Ruby are currently amd64 only. This should change shortly (hopefully days rather than weeks).

In general, if you go to https://github.com/chainguard-images/images you will be able to see which tags are wolfi and which are alpine. The alpine ones should be built for multiple archs, but we're still working on the wolfi ones.
