### ISSUE TITLE
Standardise READMEs

### ISSUE THREAD

**Issue by amouat** [chainguard-images/meta#3]
READMEs for all images should follow a template and have the same headings.

**Comment by imjasonh** [comment]
And release status badges, e.g., for distroless/static [![Create Release](https://github.com/distroless/static/actions/workflows/release.yaml/badge.svg)](https://github.com/distroless/static/actions/workflows/release.yaml)

**Comment by amouat** [comment]
Done, thanks to @jdolitsky !
