### ISSUE TITLE
Add badges with vuln count

### ISSUE THREAD

**Issue by amouat** [chainguard-images/meta#5]
Add badges with current vulnerability count. Should be at 0 (and green I guess) most of the time.

I'm hoping this is pretty easy to build using the data from the vuln scan action. There is a question about which tags to show vulns for. (Ideally all so that people can make an informed decision).

**Comment by imjasonh** [comment]
You can use shields.io to generate these shields:

https://img.shields.io/badge/trivy-0-green makes ![example green trivy badge](https://img.shields.io/badge/trivy-0-green)
https://img.shields.io/badge/trivy-3-red makes ![example red trivy badge](https://img.shields.io/badge/trivy-0-red)

We could have a table of all the tags we currently build and their statuses, something like:

| Version  | Vulnerabilities |
| ------------- | ------------- |
| `:v1.20.1`  | ![](https://img.shields.io/badge/trivy-0-green) ![](https://img.shields.io/badge/grype-3-red) ![](https://img.shields.io/badge/snyk-0-green) |
| `:v1.23.4`  | ![](https://img.shields.io/badge/trivy-0-green) ![](https://img.shields.io/badge/grype-1-red) ![](https://img.shields.io/badge/snyk-1-red) |

**Comment by amouat** [comment]
Could tie this in with #4

**Comment by jdolitsky** [comment]
done
