### ISSUE TITLE
Add Node Image

### ISSUE THREAD

**Issue by amouat** [chainguard-images/meta#9]
Add a [Node,js](https://nodejs.org/en/) image

**Comment by dlorenc** [comment]
This is done now right?

**Comment by amouat** [comment]
I think it still needs tested and an example added. But we could split those out into new issues.

**Comment by patflynn** [comment]
@amouat did we decide on the npm stuff? Should we file new issues for next quarter?

**Comment by imjasonh** [comment]
> @amouat did we decide on the npm stuff? Should we file new issues for next quarter?

Still open: https://github.com/chainguard-images/node/issues/3
